# Generated by Django 4.2.3 on 2023-07-25 07:03

import FruitipediaApp.validators.validator_profile
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(validators=[FruitipediaApp.validators.validator_profile.alpha_validator, django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(25)], verbose_name='First Name')),
                ('last_name', models.CharField(validators=[FruitipediaApp.validators.validator_profile.alpha_validator, django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)], verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Email')),
                ('password', models.CharField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(40)], verbose_name='Password')),
                ('image_url', models.URLField(null=True, verbose_name='Image URL')),
                ('age', models.IntegerField(default='default_value', null=True, verbose_name='Age')),
            ],
        ),
    ]
