# Generated by Django 4.2.3 on 2023-07-26 08:37

import FruitipediaApp.validators.validator_profile
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(default='18', null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.MaxLengthValidator(40)], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(validators=[FruitipediaApp.validators.validator_profile.alpha_validator, django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(25)], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(validators=[FruitipediaApp.validators.validator_profile.alpha_validator, django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(35)], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='password',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(20)], verbose_name='Password'),
        ),
    ]
