# Generated by Django 4.2.3 on 2024-05-09 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_profilemodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='password',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(20)], verbose_name='Password'),
        ),
    ]
