# Generated by Django 4.2.3 on 2023-07-25 07:03

import FruitipediaApp.validators.validator_fruit
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30), FruitipediaApp.validators.validator_fruit.alpha_validator], verbose_name='Name')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('nutrition', models.TextField(null=True, verbose_name='Nutrition')),
            ],
        ),
    ]
