# Generated by Django 4.2.3 on 2024-05-09 18:42

import FruitipediaApp.validators.validator_fruit
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitmodel',
            name='name',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(30), FruitipediaApp.validators.validator_fruit.alpha_validator], verbose_name='Name'),
        ),
    ]
